#!/usr/bin/env bash

exec /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Apply themes
~/.config/hypr/scripts/gtkthemes &

# Set wallpaper
hyprpaper &

# Launch bar
hyprpanel &

# Clipboard history
wl-paste --type text --watch cliphist store &
