# Application bindings
bindd = SUPER, RETURN, Terminal, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, F, File manager, exec, uwsm-app -- nautilus --new-window
bindd = SUPER ALT SHIFT, F, File manager (cwd), exec, uwsm-app -- nautilus --new-window "$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, M, Music TUI, exec, omarchy-launch-or-focus-tui cliamp
bindd = SUPER SHIFT, N, Editor, exec, omarchy-launch-editor
bindd = SUPER SHIFT, D, Docker, exec, omarchy-launch-tui lazydocker

# Overwrite existing bindings
unbind = SUPER, W
unbind = SUPER, SPACE
unbind = SUPER ALT, SPACE
unbind = SUPER, L
unbind = SUPER ALT, S
unbind = SUPER, K

# Add extra bindings
bindd = SUPER SHIFT, RETURN, Launch apps, exec, omarchy-launch-walker
bindd = SUPER SHIFT, C, Close window, killactive,
bindd = ALT SHIFT, RETURN, Omarchy menu, exec, omarchy-menu
bindd = ALT, RETURN, Browser, exec, omarchy-launch-browser

bindd = SUPER SHIFT, S, Move window to scratchpad, movetoworkspacesilent, special:scratchpad

bindd = SUPER,       J, Focus next window in layout, layoutmsg, cyclenext
bindd = SUPER,       K, Focus previous window in layout, layoutmsg, cycleprev
bindd = SUPER SHIFT, J, Swap next window in layout, layoutmsg, swapnext
bindd = SUPER SHIFT, K, Swap previous window in layout, layoutmsg, swapprev
bindd = SUPER,       H, Expand window left, resizeactive, -100 0
bindd = SUPER,       L, Shrink window left, resizeactive, 100 0
bindd = SUPER SHIFT, H, Add master window, layoutmsg, addmaster
bindd = SUPER SHIFT, L, Remove master window, layoutmsg, removemaster

bindd = SUPER, B, Show key bindings, exec, omarchy-menu-keybindings
