#!/usr/bin/env bash

time=$(date +%Y-%m-%d-%H-%M-%S)
dir="$(xdg-user-dir PICTURES)"
file="Screenshot_${time}_${RANDOM}.png"

notify_view() {
    notify-send -h string:x-canonical-private-synchronous:sys-notify-shot -u low "Copied to clipboard."
    paplay /usr/share/sounds/freedesktop/stereo/screen-capture.oga &>/dev/null &
}

countdown() {
    for sec in $(seq "$1" -1 1); do
        notify-send -h string:x-canonical-private-synchronous:sys-notify-count -t 1000 "Taking shot in : $sec"
        sleep 1
    done
}

shotnow() {
    cd "${dir}" && grim - | tee "$file" | wl-copy
    notify_view
}

shot5() {
    countdown '5'
    cd "${dir}" && grim - | tee "$file" | wl-copy
    notify_view
}

shot10() {
    countdown '10'
    cd "${dir}" && grim - | tee "$file" | wl-copy
    notify_view
}

shotwin() {
    w_pos=$(hyprctl activewindow | grep 'at:' | cut -d':' -f2 | tr -d ' ' | tail -n1)
    w_size=$(hyprctl activewindow | grep 'size:' | cut -d':' -f2 | tr -d ' ' | tail -n1 | sed s/,/x/g)
    cd "${dir}" && grim -g "$w_pos $w_size" - | tee "$file" | wl-copy
    notify_view
}

shotarea() {
    cd "${dir}" || exit 1

    geometry=$(slurp -b 20262CCC -c B4A1DBff -s B4A1DB0D -w 2 && sleep 0.3)

    if [[ -n "$geometry" ]]; then
        grim -g "$geometry" - | tee "$file" | wl-copy
        notify_view
    fi
}

if [[ ! -d "$dir" ]]; then
    mkdir -p "$dir"
fi

if [[ "$1" == "--now" ]]; then
    shotnow
elif [[ "$1" == "--in5" ]]; then
    shot5
elif [[ "$1" == "--in10" ]]; then
    shot10
elif [[ "$1" == "--win" ]]; then
    shotwin
elif [[ "$1" == "--area" ]]; then
    shotarea
else
    echo -e "Available Options : --now --in5 --in10 --win --area"
fi
